version: '3.8'

services:

  chatbot-flask:
    container_name: bot
    build:
      dockerfile: Dockerfile
      context: .
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    ports:
      - '80:5000'
